"""Fetch each app's Play Store listing into _data/play_stats.yml and images/apps.

Stores what the site shows and sorts by: rating to one decimal, installs as
the store's "10K+" range, release date, short description, and the Play URLs
of the feature graphic and icon. Values are coarse on purpose so the data file
only changes when the site would.

The images are downloaded into the repo (webp) only when their Play URL
changes. An app or image that fails keeps its previous values, and the run
exits non-zero at the end so the failure is visible.
"""

import io
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

import yaml
from google_play_scraper import app
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
APPS_FILE = ROOT / "_data" / "apps.yml"
STATS_FILE = ROOT / "_data" / "play_stats.yml"
IMAGES_DIR = ROOT / "images" / "apps"

FEATURE_SIZE = (1024, 500)
ICON_SIZE = (144, 144)


def short_installs(installs):
    """'100,000+' -> '100K+', '1,000,000+' -> '1M+', '500+' -> '500+'."""
    count = int(installs.replace(",", "").rstrip("+"))
    for size, suffix in ((1_000_000_000, "B"), (1_000_000, "M"), (1_000, "K")):
        if count >= size:
            return f"{count // size}{suffix}+"
    return f"{count}+"


def fetch(package):
    details = app(package, lang="en", country="us")
    stats = {}
    if details.get("score"):
        stats["rating"] = round(details["score"], 1)
    if details.get("installs"):
        stats["installs"] = short_installs(details["installs"])
    if details.get("released"):
        released = datetime.strptime(details["released"], "%b %d, %Y")
        stats["released"] = released.date().isoformat()
    if details.get("summary"):
        stats["description"] = " ".join(details["summary"].split())
    if details.get("headerImage"):
        stats["feature_url"] = details["headerImage"]
    if details.get("icon"):
        stats["icon_url"] = details["icon"]
    return stats


def download_webp(url, size, path):
    """Download a Play image at `size`, check its dimensions, save as webp."""
    request = urllib.request.Request(
        f"{url}=w{size[0]}-h{size[1]}", headers={"User-Agent": "Mozilla/5.0"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        image = Image.open(io.BytesIO(response.read()))
    if image.size != size:
        raise ValueError(f"expected {size[0]}x{size[1]}, got {image.size[0]}x{image.size[1]}")
    if image.mode not in ("RGB", "RGBA"):
        image = image.convert("RGBA")
    image.save(path, "WEBP", quality=90)


def sync_images(package, stats, old):
    """Download the images whose Play URL changed. Returns the number that failed."""
    failed = 0
    for key, size, name in (
        ("feature_url", FEATURE_SIZE, f"{package}-feature.webp"),
        ("icon_url", ICON_SIZE, f"{package}-icon.webp"),
    ):
        url = stats.get(key)
        path = IMAGES_DIR / name
        if not url or (old.get(key) == url and path.exists()):
            continue
        try:
            download_webp(url, size, path)
            print(f"  downloaded {name}")
        except Exception as error:
            failed += 1
            print(f"::warning::{package} {name}: {error}")
            # Keep the old URL so tomorrow's run tries again.
            if old.get(key):
                stats[key] = old[key]
            else:
                del stats[key]
    return failed


def main():
    apps = yaml.safe_load(APPS_FILE.read_text(encoding="utf-8"))
    old = {}
    if STATS_FILE.exists():
        old = yaml.safe_load(STATS_FILE.read_text(encoding="utf-8")) or {}

    stats, failed, image_failures = {}, 0, 0
    for entry in apps:
        package = entry["package"]
        previous = old.get(package, {})
        try:
            stats[package] = fetch(package)
        except Exception as error:
            failed += 1
            print(f"::warning::{package}: {error}")
            if package in old:
                stats[package] = previous
            continue
        print(package, stats[package])
        image_failures += sync_images(package, stats[package], previous)

    # Every fetch failing means the scraper is broken, not the apps: keep the
    # old file and fail the run so it shows up.
    if failed == len(apps):
        sys.exit("Every fetch failed; leaving play_stats.yml unchanged")

    STATS_FILE.write_text(
        "# Generated by .github/workflows/play-stats.yml - do not edit by hand.\n"
        + yaml.safe_dump(stats, sort_keys=False, allow_unicode=True, width=1000),
        encoding="utf-8",
    )

    if failed or image_failures:
        sys.exit(f"{failed} fetches and {image_failures} image downloads failed")


if __name__ == "__main__":
    main()
