// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    $('#twitter').mouseover(function() {
      return $('#mousing').text("Twitter");
    });
    $('#twitter').mouseout(function() {
      return $('#mousing').html("&nbsp;");
    });
    $('#play').mouseover(function() {
      return $('#mousing').text("Apps");
    });
    $('#play').mouseout(function() {
      return $('#mousing').html("&nbsp;");
    });
    $('#rss').mouseover(function() {
      return $('#mousing').text("RSS");
    });
    return $('#rss').mouseout(function() {
      return $('#mousing').html("&nbsp;");
    });
  });

}).call(this);
